title: "Tessie Bourgeois – Data Analyst junior"
logo: /img/Photo_CV.png
description:"Portfolio de Tessie Bourgeois, étudiante en M1 Mégadonnées (MEDAS, CNAM) en recherche d'alternance : Python, SQL, Power BI, SPSS AMOS, études quantitatives et qualitatives."
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
